### ISSUE TITLE
pip install breaks

### ISSUE THREAD

**Issue by sven-nm** [hipe-hist-ne/hipe-pycommons#7]
Ciao @mromanello 

Notice that is related to the last version as I had the previous version installed seamlessly. 

```
Collecting git+https://github.com/hipe-eval/HIPE-pycommons
  Cloning https://github.com/hipe-eval/HIPE-pycommons to /private/var/folders/tg/_6zh_tz94ddb53tskzx6vdhw0000gn/T/pip-req-build-snriwk9z
  Running command git clone --filter=blob:none --quiet https://github.com/hipe-eval/HIPE-pycommons /private/var/folders/tg/_6zh_tz94ddb53tskzx6vdhw0000gn/T/pip-req-build-snriwk9z
  Resolved https://github.com/hipe-eval/HIPE-pycommons to commit 40a6a024e76cd84786db46000d3ba5eef58ccf42
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [57 lines of output]
      running egg_info
      creating /private/var/folders/tg/_6zh_tz94ddb53tskzx6vdhw0000gn/T/pip-pip-egg-info-tyck5boq/hipe_commons.egg-info
      writing manifest file '/private/var/folders/tg/_6zh_tz94ddb53tskzx6vdhw0000gn/T/pip-pip-egg-info-tyck5boq/hipe_commons.egg-info/SOURCES.txt'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/tg/_6zh_tz94ddb53tskzx6vdhw0000gn/T/pip-req-build-snriwk9z/setup.py", line 9, in <module>
          setup(
        File "/Users/sven/opt/anaconda3/envs/ajmc/lib/python3.11/site-packages/setuptools/__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/sven/opt/anaconda3/envs/ajmc/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/Users/sven/opt/anaconda3/envs/ajmc/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/Users/sven/opt/anaconda3/envs/ajmc/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/Users/sven/opt/anaconda3/envs/ajmc/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/Users/sven/opt/anaconda3/envs/ajmc/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 299, in run
          self.find_sources()
        File "/Users/sven/opt/anaconda3/envs/ajmc/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 306, in find_sources
          mm.run()
        File "/Users/sven/opt/anaconda3/envs/ajmc/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 541, in run
          self.add_defaults()
        File "/Users/sven/opt/anaconda3/envs/ajmc/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 578, in add_defaults
          sdist.add_defaults(self)
        File "/Users/sven/opt/anaconda3/envs/ajmc/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 226, in add_defaults
          self._add_defaults_python()
        File "/Users/sven/opt/anaconda3/envs/ajmc/lib/python3.11/site-packages/setuptools/command/sdist.py", line 111, in _add_defaults_python
          build_py = self.get_finalized_command('build_py')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/sven/opt/anaconda3/envs/ajmc/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 299, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "/Users/sven/opt/anaconda3/envs/ajmc/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in ensure_finalized
          self.finalize_options()
        File "/Users/sven/opt/anaconda3/envs/ajmc/lib/python3.11/site-packages/setuptools/command/build_py.py", line 29, in finalize_options
          orig.build_py.finalize_options(self)
        File "/Users/sven/opt/anaconda3/envs/ajmc/lib/python3.11/site-packages/setuptools/_distutils/command/build_py.py", line 43, in finalize_options
          self.set_undefined_options('build',
        File "/Users/sven/opt/anaconda3/envs/ajmc/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 286, in set_undefined_options
          src_cmd_obj = self.distribution.get_command_obj(src_cmd)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/sven/opt/anaconda3/envs/ajmc/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 858, in get_command_obj
          klass = self.get_command_class(command)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/sven/opt/anaconda3/envs/ajmc/lib/python3.11/site-packages/setuptools/dist.py", line 893, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
                                              ^^^^^^^^^
        File "/Users/sven/opt/anaconda3/envs/ajmc/lib/python3.11/site-packages/pkg_resources/__init__.py", line 2465, in load
          return self.resolve()
                 ^^^^^^^^^^^^^^
        File "/Users/sven/opt/anaconda3/envs/ajmc/lib/python3.11/site-packages/pkg_resources/__init__.py", line 2471, in resolve
          module = __import__(self.module_name, fromlist=['__name__'], level=0)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      ModuleNotFoundError: No module named 'setuptools.command.build'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by EmanuelaBoros** [comment]
Hello @sven-nm, sorry for jumping in, but I've done a quick test, and it does **not** crash with Python 3.9.6 and 3.11.9. What version do you have?

**Comment by sven-nm** [comment]
@EmanuelaBoros Sorry for my extremely late reply. Actually, I guess I was trying to install from a specific commit, and that still fails. 

```
pip install git+https://github.com/hipe-eval/HIPE-pycommons@5ededfed8cc20b58e30de728f65cfd9e8279ed47
```
traceback: 
```
Collecting git+https://github.com/hipe-eval/HIPE-pycommons@5ededfed8cc20b58e30de728f65cfd9e8279ed47
  Cloning https://github.com/hipe-eval/HIPE-pycommons (to revision 5ededfed8cc20b58e30de728f65cfd9e8279ed47) to ./tmp/pip-req-build-hy39dg0e
  Running command git clone --filter=blob:none --quiet https://github.com/hipe-eval/HIPE-pycommons /scratch/sven/tmp/pip-req-build-hy39dg0e
  Running command git rev-parse -q --verify 'sha^5ededfed8cc20b58e30de728f65cfd9e8279ed47'
  Running command git fetch -q https://github.com/hipe-eval/HIPE-pycommons 5ededfed8cc20b58e30de728f65cfd9e8279ed47
  Running command git checkout -q 5ededfed8cc20b58e30de728f65cfd9e8279ed47
  Resolved https://github.com/hipe-eval/HIPE-pycommons to commit 5ededfed8cc20b58e30de728f65cfd9e8279ed47
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/scratch/sven/tmp/pip-req-build-hy39dg0e/setup.py", line 30
          long_description=read("README.md"),
          ^
      SyntaxError: invalid syntax
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by EmanuelaBoros** [comment]
Hello @sven-nm, you are trying to install a commit https://github.com/hipe-eval/HIPE-pycommons/commit/5ededfed8cc20b58e30de728f65cfd9e8279ed47 that had an issue that was solved here https://github.com/hipe-eval/HIPE-pycommons/commit/4262f3746ddc0ab80697829f4792ce09fb5276cc.

Can you install the latest version?

Best

**Comment by sven-nm** [comment]
Ciao Ema I can in deed install the latest version, you can safely close the issue 😊
